class constant:

    correction = {
        "loofahh": "loofah",
        "boothes": "booths",
        "baggages": "baggage",
        "tellies": "telly",
        "valises": "valise",
        "lundry": "laundry",
        "washbowls": "wash bowls",
        "convectors": "convection",
        "convector": "convection",
        "xeroxes": "xerox",
        "doorcases": "door cases",
        "doorcase": "door case",
        "washbowl": "wash bowl",
        "hatrack": "hat rack",
        "hatracks": "hat racks",
        "coatrack": "coat rack",
        "coatracks": "coat racks",
        "swiffers": "swiffer",
        "doorframes": "doorframe",
        "hoverboards": "hoverboard",
        "bycicles": "bicycles",
        "bycicle": "bicycle",
        "quadcopters": "quadcopter",
        "tupperwares": "tupperware",
        "sanitzer": "sanitizer",
        "dustpans": "dustpan",
        "dumbell": "dumbbell",
        "dumbells": "dumbbells",
        "cardboards": "cardboard",
        "beachballs": "beachball",
        "carseat": "car seat",
        "carseats": "car seats",
        "kinects": "kinect",
        "stepstools": "step stools",
        "stepstool": "step stools",
        "roombas": "roomba",
        "loofas": "loofah",
        "loofa": "loofah",
        "stovetops": "stovetop",
        "bedframes": "bed frames",
        "bedframe": "bed frame",
    }
